### PR TITLE
Translate to polish and add links to other languages

### PR DESCRIPTION
**Pull request by ticotaco72**
adding links to other langs can make it easier to report things for people that are for the first time on github

### CODE REVIEW

**Comment by peppy** [comment]
these language readmes are quite weird in my eyes, since all reports in this repo need to be in english.

**Comment by TPGPL** [comment]
in my opinion the translations should be deleted as the issues must still be in English and those translations aren't even viewed on the repo overview unless you click on them in file view

**Comment by TPGPL** [comment]
also quality of this translation is questionable so i would advise to close this pull request until a revise is prepared

**Comment by smoogipoo** [comment]
Closing as I think we're all in agreement.

**Pull request closed without merging**
